### ISSUE TITLE
Set PJSIP as optional.

### ISSUE THREAD

**Issue by alvaro-gh** [dougbtv/install-asterisk#13]
Maybe classic SIP stack is not so widely used but I still use it in some deployments. This role could be a little more flexible setting:
* A default var like `use_pjsip` in defaults/main.yml.
* A conditional include `when use_pjsip` in tasks/install.yml.

**Comment by dougbtv** [comment]
@mxdlx -- sounds great! I like the suggestion, happy to take a PR on it, that approach sounds good to me.

**Comment by dougbtv** [comment]
Fixed in #14, thanks for the report and the contribution!
