### ISSUE TITLE
kernel-devel with ansible_kernel not found

### ISSUE THREAD

**Issue by alvaro-gh** [dougbtv/install-asterisk#15]
I was testing earlier with a Centos 7 Generic Cloud Image v1711 for x86_64 (8700235) and yum could not find kernel-devel-{{ ansible_kernel }} (I don't remember specific kernel). 
I tried adding `update_cache` to [this task](https://github.com/dougbtv/install-asterisk/blob/52109ff365e66ad3eb503eeed95cae4484c48b75/tasks/install_yum_packages.yml#L7) but it did not work.
I set the [kernel-devel item](https://github.com/dougbtv/install-asterisk/blob/52109ff365e66ad3eb503eeed95cae4484c48b75/tasks/install_yum_packages.yml#L22) as `kernel-devel` only and installation went through with no relevant issues.
According to [this piece of CentOS docs](https://wiki.centos.org/HowTos/I_need_the_Kernel_Source) CentOS 7 only has kernel-devel. I may be necessary to split package installation between CentOS 7 and earlier versions.

**Comment by dougbtv** [comment]
Thanks for the report -- happy to take another PR. Personally, I'm ok with making CentOS 6 unsupported and change it to just `kernel-devel` without the `{{ ansible_kernel }}` suffix.

edit: Also thanks for the details and reference links!!

**Comment by dougbtv** [comment]
Fixed in #16 !
