### ISSUE TITLE
Configure and install ODBC

### ISSUE THREAD

**Issue by ktarbet** [dougbtv/install-asterisk#6]
pre-asterisk compile steps:  (From Asterisk the Definitive Guide)

  * install packages: unixODBC unixODBC-devel libtool-ltdl libtool-ltdl-devel
  * install database specific package postgresql-odbc 
  * configure /etc/odbcinst.ini

If this sounds practical?  I'll volunteer -- However, I would need some high level guidance from @dougbtv

**Comment by dougbtv** [comment]
Karl, I'd appreciate the contribution for sure! Personally, I'd be most
interested if it was an option to have ODBC support, E.g. as a role
variable to optionally include it. But, I think it'd be very worthwhile to
include.

Thanks for opening issue, feel free to ask away or point me to a fork if
you want a set of eyes.

**Comment by ktarbet** [comment]
I agree making ODBC optional is the way to approach it.  

So would the variable be in vars/main.yml?   
How about iasterisk_odbc_support: false|true

**Comment by dougbtv** [comment]
That sounds absolutely perfect, and you can follow the similar structure of optional inclusion by adding a conditional include in `install-asterisk/tasks/main.yml` 

Like:

```
- include: odbc.yml
  when: iasterisk_odbc_support
```

(thanks again!)

**Comment by ktarbet** [comment]
Thanks for the guidance.     I've started with 2adebd1 
 next step:  I'll check if odbc is detected by the asterisk build system.

**Comment by ktarbet** [comment]
Will you please take a look? --  This is PostgreSQL biased at this point.   

https://github.com/dougbtv/install-asterisk/compare/master...ktarbet:master

**Comment by dougbtv** [comment]
Big huge thumbs up / LGTM from me (from glancing, didn't try it out). The PostgreSQL bias is absolutely fine by me -- can always be made less opinionated later, but, that's a great way to start. Sorry so slow on the review.

**Comment by ktarbet** [comment]
Thanks for the review! -- I'll be doing more testing before I click make pull request.
