### ISSUE TITLE
lost dependency

### ISSUE THREAD

**Issue by ivn86** [dougbtv/install-asterisk#8]
I tested your playbook on LXC-container with CentOS7. There is no preinstalled 'make' utility.

>TASK [dougbtv.install-asterisk : Build pjsip from tarball] *********************
changed: [192.168.23.21] => (item=./configure --prefix=/usr --libdir=/usr/lib64 --enable-shared --disable-sound --disable-resample --disable-video --disable-opencore-amr)
>failed: [192.168.23.21] (item=make dep) => {"cmd": "make dep", "failed": true, "item": "make dep", "msg": "[Errno 2] Нет такого файла или каталога", "rc": 2}
>failed: [192.168.23.21] (item=make) => {"cmd": "make", "failed": true, "item": "make", "msg": "[Errno 2] Нет такого файла или каталога", "rc": 2}
>failed: [192.168.23.21] (item=make install) => {"cmd": "make install", "failed": true, "item": "make install", "msg": "[Errno 2] Нет такого файла или каталога", "rc": 2}`

Add 'make' to pre-requisites list of packages.

**Comment by dougbtv** [comment]
Hrmmm, yeah this has been tested with CentOS minimal and CentOS Generic Cloud image. I'll add make, none-the-less, but, would be even more helpful if you could figure out what other deps are necessary too cause it might not be the only one.

Just tested with CentOS Generic Cloud to see if something changed in the dependency trees, but, still worked.

If you're interested, I also have Dockerfiles for Asterisk, too. https://github.com/dougbtv/docker-asterisk
